include: package:flutter_lints/flutter.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - windows/**
linter:
  rules:
    unawaited_futures: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_print: true
    directives_ordering: true
